=== hmcts/sscs-tribunals-case-api/src/main/resources/config/schema/sscs-bulk-scan-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "BulkScan",
  "type": "object",
  "properties": {
    "is_benefit_type_pip":  {"type": "string"},
    "is_benefit_type_esa":  {"type": "string"},
    "is_benefit_type_uc":  {"type": "string"},
    "contains_mrn": {"type": "string"},
    "mrn_date": {"type": "string"},
    "benefit_type_description": {"type": "string"},
    "person1_title": {"type": "string"},
    "person1_first_name": {"type": "string"},
    "person1_last_name": {"type": "string"},
    "person1_address_line1": {"type": "string"},
    "person1_address_line2": {"type": "string"},
    "person1_address_line3": {"type": "string"},
    "person1_address_line4": {"type": "string"},
    "person1_postcode": {"type": "string"},
    "person1_phone": {"type": "string"},
    "person1_mobile": {"type": "string"},
    "person1_email": {"type": "string"},
    "person1_want_sms_notifications": {"type": "string"},
    "person1_dob": {"type": "string"},
    "person1_nino": {"type": "string"},
    "person2_title": {"type": "string"},
    "person2_first_name": {"type": "string"},
    "person2_last_name": {"type": "string"},
    "person2_address_line1": {"type": "string"},
    "person2_address_line2": {"type": "string"},
    "person2_address_line3": {"type": "string"},
    "person2_address_line4": {"type": "string"},
    "person2_postcode": {"type": "string"},
    "person2_dob": {"type": "string"},
    "person2_nino": {"type": "string"},
    "representative_company": {"type": "string"},
    "representative_address_line1": {"type": "string"},
    "representative_address_line2": {"type": "string"},
    "representative_address_line3": {"type": "string"},
    "representative_address_line4": {"type": "string"},
    "representative_postcode": {"type": "string"},
    "representative_phone": {"type": "string"},
    "representative_email": {"type": "string"},
    "representative_mobile": {"type": "string"},
    "representative_want_sms_notifications": {"type": "string"},
    "representative_title": {"type": "string"},
    "representative_first_name": {"type": "string"},
    "representative_last_name": {"type": "string"},
    "appeal_grounds": {"type": "string"},
    "appeal_late_reason": {"type": "string"},
    "is_hearing_type_oral": {"type": "string"},
    "is_hearing_type_paper": {"type": "string"},
    "hearing_options_exclude_dates": {"type": "string"},
    "hearing_support_arrangements": {"type": "string"},
    "hearing_options_hearing_loop": {"type": "string"},
    "hearing_options_accessible_hearing_rooms": {"type": "string"},
    "hearing_options_sign_language_interpreter": {"type": "string"},
    "hearing_options_language_type": {"type": "string"},
    "hearing_options_dialect": {"type": "string"},
    "hearing_options_sign_language_type": {"type": "string"},
    "agree_less_hearing_notice": {"type": "string"},
    "signature_name": {"type": "string"},
    "signature_appeal_date": {"type": "string"},
    "office": {"type": "string"},
    "tell_tribunal_about_dates": {"type": "string"},
    "hearing_type_telephone": {"type": "string"},
    "hearing_telephone_number": {"type": "string"},
    "hearing_type_video": {"type": "string"},
    "hearing_video_email": {"type": "string"},
    "hearing_type_face_to_face": {"type": "string"},
    "appeal_grounds_2": {"type": "string"},
    "is_benefit_type_other": {"type": "string"},
    "benefit_type_other": {"type": "string"},
    "form_type": {"type": "string"}
  },
  "additionalProperties": false
}

=== hmcts/sscs-tribunals-case-api/src/test/resources/schema/valid_ocr_agreed.json
{
  "contains_mrn": "true",
  "mrn_date": "09/11/2018",
  "benefit_type_description": "Employment Support Allowance",
  "person1_title": "Mr",
  "person1_first_name": "John",
  "person1_last_name": "Smith",
  "person1_address_line1": "2 Drake Close",
  "person1_address_line2": "Hutton",
  "person1_address_line3": "Brentwood",
  "person1_address_line4": "Essex",
  "person1_postcode": "SE166RS",
  "person1_phone": "01895733303",
  "person1_mobile": "07832882849",
  "person1_dob": "11/11/1976",
  "person1_nino": "BB000000B",
  "person2_title": "Mrs",
  "person2_first_name": "Sarah",
  "person2_last_name": "Smith",
  "person2_address_line1": "10 Drake Close",
  "person2_address_line2": "Hutton",
  "person2_address_line3": "Brentwood",
  "person2_address_line4": "Essex",
  "person2_postcode": "SE166RS",
  "person2_dob": "09/12/1979",
  "person2_nino": "BB000000B",
  "representative_company": "ABC Advisory Services",
  "representative_address_line1": "63 Grovehill Road",
  "representative_address_line2": "The Square",
  "representative_address_line3": "Redhill",
  "representative_address_line4": "Surrey",
  "representative_postcode": "RH1 6RE",
  "representative_phone": "02072323231",
  "representative_title": "Mr",
  "representative_first_name": "Peter",
  "representative_last_name": "Hyland",
  "appeal_grounds": "see scanned SSCS1 form",
  "appeal_late_reason": "see scanned SSCS1 form",
  "is_hearing_type_oral": "true",
  "is_hearing_type_paper": "false",
  "hearing_options_exclude_dates": "I cannot attend on Mondays and I am on holiday in October.",
  "hearing_support_arrangements": "Wheelchair access" ,
  "hearing_options_hearing_loop": "Yes" ,
  "hearing_options_accessible_hearing_rooms": "No" ,
  "hearing_options_sign_language_interpreter": "No" ,
  "hearing_options_language_type": "Spanish" ,
  "hearing_options_dialect": "" ,
  "hearing_options_sign_language_type": "" ,
  "agree_less_hearing_notice": "true" ,
  "signature_name": "Sarah Smith" ,
  "signature_appeal_date": "01/04/2018"
}
